version: '3'

services:
  # client:
    # TODO

  # server:
    # TODO

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

# template from another app:
  # website:
  #   build: ./apps/website
  #   # image: 985764892725.dkr.ecr.us-east-1.amazonaws.com/website:latest
  #   environment:
  #     environment: ${ENVIRONMENT}
  #   # command: yarn start
  #   # volumes:
  #     # - ./apps/website/:/usr/src/app/
