// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appContainer': string;
  'base-container': string;
  'baseFont': string;
  'spin': string;
  'svgContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
